import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from Bio import Entrez
from datetime import datetime, timedelta
from zoneinfo import ZoneInfo
import os

# =========================
# Global settings
# =========================
TZ = ZoneInfo("Asia/Shanghai")  # 中国时区（无夏令时）

EMAIL_SENDER = os.environ.get("EMAIL_SENDER")
EMAIL_PASSWORD = os.environ.get("EMAIL_PASSWORD")
EMAIL_RECEIVER_STR = os.environ.get("EMAIL_RECEIVER")
ENTREZ_EMAIL = os.environ.get("ENTREZ_EMAIL")

if EMAIL_RECEIVER_STR:
    EMAIL_RECEIVER = [e.strip() for e in EMAIL_RECEIVER_STR.split(",") if e.strip()]
else:
    EMAIL_RECEIVER = []


KEYWORDS = ["intensive blood pressure", "frailty", "C-reactive protein", "inflammation", "biological age"]

# =========================
# PubMed fetch
# =========================
def fetch_articles(datetype: str = "edat", retmax: int = 100):
    """
    datetype:
      - "edat": PubMed收录/更新日期（更贴合“昨日新增”digest）
      - "pdat": 发表日期（更贴合“昨日发表”）
    """
    if not ENTREZ_EMAIL:
        print("Error: ENTREZ_EMAIL not set.")
        return []

    Entrez.email = ENTREZ_EMAIL

    # 以中国日期定义“昨天”
    today_cn = datetime.now(TZ).date()
    yesterday_cn = today_cn - timedelta(days=1)
    mindate = yesterday_cn.strftime("%Y/%m/%d")
    maxdate = yesterday_cn.strftime("%Y/%m/%d")

    # term 只做关键词逻辑；日期用 mindate/maxdate/datetype 控制
    search_terms = [f'"{term}"[Title/Abstract]' for term in KEYWORDS]
    pubmed_query_terms = " OR ".join(search_terms)
    term = f"({pubmed_query_terms})"

    print(f"Searching PubMed: {term}")
    print(f"Date window ({datetype}) in China date: {mindate} to {maxdate}")

    try:
        handle = Entrez.esearch(
            db="pubmed",
            term=term,
            mindate=mindate,
            maxdate=maxdate,
            datetype=datetype,
            retmax=retmax,
        )
        record = Entrez.read(handle)
        handle.close()

        id_list = record.get("IdList", [])
        if not id_list:
            print("No articles found in search results.")
            return []

        handle = Entrez.efetch(
            db="pubmed",
            id=",".join(id_list),
            rettype="medline",
            retmode="xml",
        )
        articles = Entrez.read(handle)
        handle.close()

    except Exception as e:
        print(f"Error during PubMed API call: {e}")
        return []

    digest_data = []
    for article in articles.get("PubmedArticle", []):
        try:
            medline = article["MedlineCitation"]["Article"]
            title = medline.get("ArticleTitle", "No Title")
            journal = medline.get("Journal", {}).get("Title", "No Journal")

            pmid = article["MedlineCitation"]["PMID"]
            link = f"https://pubmed.ncbi.nlm.nih.gov/{pmid}/"

            author_list = medline.get("AuthorList", [])
            if not author_list:
                authors = "No Authors Listed"
            elif len(author_list) == 1:
                authors = f"{author_list[0].get('LastName', '')} {author_list[0].get('Initials', '')}"
            else:
                first = f"{author_list[0].get('LastName', '')} {author_list[0].get('Initials', '')}"
                last = f"{author_list[-1].get('LastName', '')} {author_list[-1].get('Initials', '')}"
                authors = f"{first} ... {last}"

            digest_data.append(
                {"title": title, "authors": authors, "journal": journal, "url": link}
            )

        except Exception as e:
            print(f"Skipping article due to parsing error: {e}")
            continue

    return digest_data


# =========================
# Email format + send
# =========================
def format_html_email(data):
    html = """
    <html>
    <head>
    <style>
        table {width: 100%; border-collapse: collapse; font-family: Arial, sans-serif;}
        th {background-color: #003366; color: white; padding: 10px; text-align: left;}
        td {border-bottom: 1px solid #ddd; padding: 8px; text-align: left; vertical-align: top;}
        tr:nth-child(even) {background-color: #f2f2f2;}
        .title {font-weight: bold; color: #0056b3; text-decoration: none;}
        .title:hover {text-decoration: underline;}
        .journal {font-style: italic; color: #666;}
    </style>
    </head>
    <body>
    <h2>Daily Siyu Zhiping Yuxiang Literature Digest</h2>
    <table>
        <tr>
            <th style="width: 50%;">Title (Click to Read)</th>
            <th style="width: 25%;">First & Last Author</th>
            <th style="width: 25%;">Journal</th>
        </tr>
    """

    for row in data:
        html += f"""
        <tr>
            <td><a href="{row['url']}" class="title">{row['title']}</a></td>
            <td>{row['authors']}</td>
            <td class="journal">{row['journal']}</td>
        </tr>
        """

    html += """
    </table>
    <p><em>Generated by Dr. Yu Xiang using GitHub Actions</em></p>
    </body>
    </html>
    """
    return html


def send_email(html_content):
    if not EMAIL_SENDER or not EMAIL_PASSWORD or not EMAIL_RECEIVER:
        print("Error: Email credentials or receiver list not set.")
        return

    msg = MIMEMultipart()
    msg["From"] = EMAIL_SENDER
    msg["To"] = ", ".join(EMAIL_RECEIVER)

    # 邮件标题日期按中国时区
    subject_date = datetime.now(TZ).strftime("%Y-%m-%d")
    msg["Subject"] = f"Siyu Zhiping YuXiang Literature Digest: {KEYWORDS[0]} ({subject_date})"

    msg.attach(MIMEText(html_content, "html"))

    try:
        server = smtplib.SMTP("smtp.gmail.com", 587)
        server.starttls()
        server.login(EMAIL_SENDER, EMAIL_PASSWORD)
        server.sendmail(EMAIL_SENDER, EMAIL_RECEIVER, msg.as_string())
        server.quit()
        print(f"Email successfully sent to {', '.join(EMAIL_RECEIVER)}")
    except Exception as e:
        print(f"Failed to send email: {e}")
        if "authentication failed" in str(e).lower():
            print("Authentication failed. Use Google App Password (not account password).")


if __name__ == "__main__":
    if not EMAIL_PASSWORD or not ENTREZ_EMAIL:
        print("Agent could not run. Check that EMAIL_PASSWORD and ENTREZ_EMAIL environment variables are set.")
    else:
        data = fetch_articles(datetype="edat", retmax=100)
        if data:
            html = format_html_email(data)
            send_email(html)
        else:
            print("No new articles found for yesterday. Email not sent.")
